name: ğŸš€ CI/CD - Build & Test (Microservices Infra)

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente de destino"
        required: true
        default: "dev"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  IMAGE_CACHE_DIR: /tmp/.buildx-cache
  CONTA_SERVICE_PATH: ./../conta-service
  KAFKA_SERVICE_PATH: ./../kafka-service
  INFRA_PATH: ./infra

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: â˜• Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: ğŸ§± Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ’¾ Cache Buildx
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: ğŸ”¨ Build Java Services
        run: |
          cd $CONTA_SERVICE_PATH && mvn -B clean package -DskipTests && cd -
          cd $KAFKA_SERVICE_PATH && mvn -B clean package -DskipTests && cd -

      - name: ğŸ³ Build Docker Images
        run: docker compose --env-file $INFRA_PATH/.env -f $INFRA_PATH/docker-compose.yml build --progress=plain

      - name: ğŸ§ª Test Container Up
        run: |
          docker compose --env-file $INFRA_PATH/.env -f $INFRA_PATH/docker-compose.yml up -d
          sleep 15
          docker ps
        continue-on-error: true

      - name: ğŸ§¹ Stop Containers
        run: docker compose --env-file $INFRA_PATH/.env -f $INFRA_PATH/docker-compose.yml down -v
        continue-on-error: true
